const url='https://restcountries.com/v3.1/all'

async function country(){
const response=await fetch(url)
const result = await response.json()
console.log(result)

result.map((country)=>{
console.log(country.flags.png)
})

}
country()
//result
// https://flagcdn.com/w320/de.png
// script.js:9 https://flagcdn.com/w320/ma.png
// script.js:9 https://flagcdn.com/w320/be.png
// script.js:9 https://flagcdn.com/w320/ck.png
// script.js:9 https://flagcdn.com/w320/ec.png
// script.js:9 https://flagcdn.com/w320/kn.png
// script.js:9 https://flagcdn.com/w320/rw.png
// script.js:9 https://flagcdn.com/w320/gy.png
// script.js:9 https://flagcdn.com/w320/mp.png
// script.js:9 https://flagcdn.com/w320/bw.png
// script.js:9 https://flagcdn.com/w320/bv.png
// script.js:9 https://flagcdn.com/w320/cn.png
// script.js:9 https://flagcdn.com/w320/gd.png
// script.js:9 https://flagcdn.com/w320/sn.png
// script.js:9 https://flagcdn.com/w320/gu.png
// script.js:9 https://flagcdn.com/w320/cg.png
// script.js:9 https://flagcdn.com/w320/th.png
// script.js:9 https://flagcdn.com/w320/jo.png
// script.js:9 https://flagcdn.com/w320/co.png
// script.js:9 https://flagcdn.com/w320/pn.png
// script.js:9 https://flagcdn.com/w320/no.png
// script.js:9 https://flagcdn.com/w320/km.png
// script.js:9 https://flagcdn.com/w320/tf.png
// script.js:9 https://flagcdn.com/w320/cv.png
// script.js:9 https://flagcdn.com/w320/cy.png
// script.js:9 https://flagcdn.com/w320/ki.png
// script.js:9 https://flagcdn.com/w320/cf.png
// script.js:9 https://flagcdn.com/w320/bq.png
// script.js:9 https://flagcdn.com/w320/pr.png
// script.js:9 https://flagcdn.com/w320/cc.png
// script.js:9 https://flagcdn.com/w320/ps.png
// script.js:9 https://flagcdn.com/w320/tm.png
// script.js:9 https://flagcdn.com/w320/io.png
// script.js:9 https://flagcdn.com/w320/qa.png
// script.js:9 https://flagcdn.com/w320/gl.png
// script.js:9 https://flagcdn.com/w320/ro.png
// script.js:9 https://flagcdn.com/w320/sh.png
// script.js:9 https://flagcdn.com/w320/nu.png
// script.js:9 https://flagcdn.com/w320/in.png
// script.js:9 https://flagcdn.com/w320/re.png
// script.js:9 https://flagcdn.com/w320/uz.png
// script.js:9 https://flagcdn.com/w320/am.png
// script.js:9 https://flagcdn.com/w320/kw.png
// script.js:9 https://flagcdn.com/w320/sx.png
// script.js:9 https://flagcdn.com/w320/bg.png
// script.js:9 https://flagcdn.com/w320/il.png
// script.js:9 https://flagcdn.com/w320/uy.png
// script.js:9 https://flagcdn.com/w320/vu.png
// script.js:9 https://flagcdn.com/w320/vn.png
// script.js:9 https://flagcdn.com/w320/as.png
// script.js:9 https://flagcdn.com/w320/bf.png
// script.js:9 https://flagcdn.com/w320/pa.png
// script.js:9 https://flagcdn.com/w320/gf.png
// script.js:9 https://flagcdn.com/w320/iq.png
// script.js:9 https://flagcdn.com/w320/tw.png
// script.js:9 https://flagcdn.com/w320/ci.png
// script.js:9 https://flagcdn.com/w320/lk.png
// script.js:9 https://flagcdn.com/w320/md.png
// script.js:9 https://flagcdn.com/w320/gb.png
// script.js:9 https://flagcdn.com/w320/gr.png
// script.js:9 https://flagcdn.com/w320/st.png
// script.js:9 https://flagcdn.com/w320/ml.png
// script.js:9 https://flagcdn.com/w320/za.png
// script.js:9 https://flagcdn.com/w320/is.png
// script.js:9 https://flagcdn.com/w320/kr.png
// script.js:9 https://flagcdn.com/w320/cl.png
// script.js:9 https://flagcdn.com/w320/mu.png
// script.js:9 https://flagcdn.com/w320/xk.png
// script.js:9 https://flagcdn.com/w320/si.png
// script.js:9 https://flagcdn.com/w320/cz.png
// script.js:9 https://flagcdn.com/w320/sm.png
// script.js:9 https://flagcdn.com/w320/by.png
// script.js:9 https://flagcdn.com/w320/ge.png
// script.js:9 https://flagcdn.com/w320/ch.png
// script.js:9 https://flagcdn.com/w320/cu.png
// script.js:9 https://flagcdn.com/w320/nf.png
// script.js:9 https://flagcdn.com/w320/cd.png
// script.js:9 https://flagcdn.com/w320/mf.png
// script.js:9 https://flagcdn.com/w320/se.png
// script.js:9 https://flagcdn.com/w320/hu.png
// script.js:9 https://flagcdn.com/w320/aw.png
// script.js:9 https://flagcdn.com/w320/ae.png
// script.js:9 https://flagcdn.com/w320/me.png
// script.js:9 https://flagcdn.com/w320/kp.png
// script.js:9 https://flagcdn.com/w320/tj.png
// script.js:9 https://flagcdn.com/w320/ly.png
// script.js:9 https://flagcdn.com/w320/ye.png
// script.js:9 https://flagcdn.com/w320/nl.png
// script.js:9 https://flagcdn.com/w320/hm.png
// script.js:9 https://flagcdn.com/w320/nc.png
// script.js:9 https://flagcdn.com/w320/kz.png
// script.js:9 https://flagcdn.com/w320/vg.png
// script.js:9 https://flagcdn.com/w320/lb.png
// script.js:9 https://flagcdn.com/w320/ng.png
// script.js:9 https://flagcdn.com/w320/ag.png
// script.js:9 https://flagcdn.com/w320/pl.png
// script.js:9 https://flagcdn.com/w320/ba.png
// script.js:9 https://flagcdn.com/w320/au.png
// script.js:9 https://flagcdn.com/w320/dz.png
// script.js:9 https://flagcdn.com/w320/mg.png
// script.js:9 https://flagcdn.com/w320/tt.png
// script.js:9 https://flagcdn.com/w320/sr.png
// script.js:9 https://flagcdn.com/w320/np.png
// script.js:9 https://flagcdn.com/w320/id.png
// script.js:9 https://flagcdn.com/w320/az.png
// script.js:9 https://flagcdn.com/w320/es.png
// script.js:9 https://flagcdn.com/w320/sv.png
// script.js:9 https://flagcdn.com/w320/hk.png
// script.js:9 https://flagcdn.com/w320/tk.png
// script.js:9 https://flagcdn.com/w320/mh.png
// script.js:9 https://flagcdn.com/w320/ru.png
// script.js:9 https://flagcdn.com/w320/lc.png
// script.js:9 https://flagcdn.com/w320/tv.png
// script.js:9 https://flagcdn.com/w320/gq.png
// script.js:9 https://flagcdn.com/w320/my.png
// script.js:9 https://flagcdn.com/w320/mw.png
// script.js:9 https://flagcdn.com/w320/sc.png
// script.js:9 https://flagcdn.com/w320/mt.png
// script.js:9 https://flagcdn.com/w320/dm.png
// script.js:9 https://flagcdn.com/w320/om.png
// script.js:9 https://flagcdn.com/w320/ao.png
// script.js:9 https://flagcdn.com/w320/pt.png
// script.js:9 https://flagcdn.com/w320/cm.png
// script.js:9 https://flagcdn.com/w320/ee.png
// script.js:9 https://flagcdn.com/w320/er.png
// script.js:9 https://flagcdn.com/w320/mr.png
// script.js:9 https://flagcdn.com/w320/ms.png
// script.js:9 https://flagcdn.com/w320/ca.png
// script.js:9 https://flagcdn.com/w320/lu.png
// script.js:9 https://flagcdn.com/w320/al.png
// script.js:9 https://flagcdn.com/w320/pm.png
// script.js:9 https://flagcdn.com/w320/yt.png
// script.js:9 https://flagcdn.com/w320/fj.png
// script.js:9 https://flagcdn.com/w320/sl.png
// script.js:9 https://flagcdn.com/w320/tc.png
// script.js:9 https://flagcdn.com/w320/cw.png
// script.js:9 https://flagcdn.com/w320/ua.png
// script.js:9 https://flagcdn.com/w320/mk.png
// script.js:9 https://flagcdn.com/w320/ad.png
// script.js:9 https://flagcdn.com/w320/na.png
// script.js:9 https://flagcdn.com/w320/ws.png
// script.js:9 https://flagcdn.com/w320/sy.png
// script.js:9 https://flagcdn.com/w320/ar.png
// script.js:9 https://flagcdn.com/w320/eh.png
// script.js:9 https://flagcdn.com/w320/mz.png
// script.js:9 https://flagcdn.com/w320/gn.png
// script.js:9 https://flagcdn.com/w320/tn.png
// script.js:9 https://flagcdn.com/w320/fk.png
// script.js:9 https://flagcdn.com/w320/ls.png
// script.js:9 https://flagcdn.com/w320/hr.png
// script.js:9 https://flagcdn.com/w320/lr.png
// script.js:9 https://flagcdn.com/w320/pg.png
// script.js:9 https://flagcdn.com/w320/fi.png
// script.js:9 https://flagcdn.com/w320/aq.png
// script.js:9 https://flagcdn.com/w320/bi.png
// script.js:9 https://flagcdn.com/w320/bo.png
// script.js:9 https://flagcdn.com/w320/tg.png
// script.js:9 https://flagcdn.com/w320/bb.png
// script.js:9 https://flagcdn.com/w320/gi.png
// script.js:9 https://flagcdn.com/w320/et.png
// script.js:9 https://flagcdn.com/w320/td.png
// script.js:9 https://flagcdn.com/w320/gm.png
// script.js:9 https://flagcdn.com/w320/nz.png
// script.js:9 https://flagcdn.com/w320/um.png
// script.js:9 https://flagcdn.com/w320/tl.png
// script.js:9 https://flagcdn.com/w320/tr.png
// script.js:9 https://flagcdn.com/w320/kh.png
// script.js:9 https://flagcdn.com/w320/lt.png
// script.js:9 https://flagcdn.com/w320/sd.png
// script.js:9 https://flagcdn.com/w320/ai.png
// script.js:9 https://flagcdn.com/w320/it.png
// script.js:9 https://flagcdn.com/w320/mv.png
// script.js:9 https://flagcdn.com/w320/pf.png
// script.js:9 https://flagcdn.com/w320/at.png
// script.js:9 https://flagcdn.com/w320/bz.png
// script.js:9 https://flagcdn.com/w320/kg.png
// script.js:9 https://flagcdn.com/w320/la.png
// script.js:9 https://flagcdn.com/w320/do.png
// script.js:9 https://flagcdn.com/w320/hn.png
// script.js:9 https://flagcdn.com/w320/sz.png
// script.js:9 https://flagcdn.com/w320/gw.png
// script.js:9 https://flagcdn.com/w320/ne.png
// script.js:9 https://flagcdn.com/w320/pe.png
// script.js:9 https://flagcdn.com/w320/bh.png
// script.js:9 https://flagcdn.com/w320/bl.png
// script.js:9 https://flagcdn.com/w320/bn.png
// script.js:9 https://flagcdn.com/w320/ky.png
// script.js:9 https://flagcdn.com/w320/py.png
// script.js:9 https://flagcdn.com/w320/bj.png
// script.js:9 https://flagcdn.com/w320/ir.png
// script.js:9 https://flagcdn.com/w320/mo.png
// script.js:9 https://flagcdn.com/w320/mx.png
// script.js:9 https://flagcdn.com/w320/je.png
// script.js:9 https://flagcdn.com/w320/so.png
// script.js:9 https://flagcdn.com/w320/lv.png
// script.js:9 https://flagcdn.com/w320/tz.png
// script.js:9 https://flagcdn.com/w320/ve.png
// script.js:9 https://flagcdn.com/w320/mn.png
// script.js:9 https://flagcdn.com/w320/cr.png
// script.js:9 https://flagcdn.com/w320/to.png
// script.js:9 https://flagcdn.com/w320/br.png
// script.js:9 https://flagcdn.com/w320/zw.png
// script.js:9 https://flagcdn.com/w320/bt.png
// script.js:9 https://flagcdn.com/w320/ke.png
// script.js:9 https://flagcdn.com/w320/vc.png
// script.js:9 https://flagcdn.com/w320/ax.png
// script.js:9 https://flagcdn.com/w320/im.png
// script.js:9 https://flagcdn.com/w320/ie.png
// script.js:9 https://flagcdn.com/w320/ht.png
// script.js:9 https://flagcdn.com/w320/mm.png
// script.js:9 https://flagcdn.com/w320/gp.png
// script.js:9 https://flagcdn.com/w320/jm.png
// script.js:9 https://flagcdn.com/w320/bs.png
// script.js:9 https://flagcdn.com/w320/fr.png
// script.js:9 https://flagcdn.com/w320/sg.png
// script.js:9 https://flagcdn.com/w320/wf.png
// script.js:9 https://flagcdn.com/w320/fo.png
// script.js:9 https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png
// script.js:9 https://flagcdn.com/w320/sj.png
// script.js:9 https://flagcdn.com/w320/ss.png
// script.js:9 https://flagcdn.com/w320/rs.png
// script.js:9 https://flagcdn.com/w320/va.png
// script.js:9 https://flagcdn.com/w320/ni.png
// script.js:9 https://flagcdn.com/w320/ug.png
// script.js:9 https://flagcdn.com/w320/us.png
// script.js:9 https://flagcdn.com/w320/eg.png
// script.js:9 https://flagcdn.com/w320/mq.png
// script.js:9 https://flagcdn.com/w320/ph.png
// script.js:9 https://flagcdn.com/w320/gs.png
// script.js:9 https://flagcdn.com/w320/zm.png
// script.js:9 https://flagcdn.com/w320/sb.png
// script.js:9 https://flagcdn.com/w320/gh.png
// script.js:9 https://flagcdn.com/w320/ga.png
// script.js:9 https://flagcdn.com/w320/pk.png
// script.js:9 https://flagcdn.com/w320/sa.png
// script.js:9 https://flagcdn.com/w320/gg.png
// script.js:9 https://flagcdn.com/w320/gt.png
// script.js:9 https://flagcdn.com/w320/nr.png
// script.js:9 https://flagcdn.com/w320/mc.png
// script.js:9 https://flagcdn.com/w320/cx.png
// script.js:9 https://flagcdn.com/w320/jp.png
// script.js:9 https://flagcdn.com/w320/li.png
// script.js:9 https://flagcdn.com/w320/pw.png
// script.js:9 https://flagcdn.com/w320/dj.png
// script.js:9 https://flagcdn.com/w320/vi.png
// script.js:9 https://flagcdn.com/w320/bm.png
// script.js:9 https://flagcdn.com/w320/sk.png
// script.js:9 https://flagcdn.com/w320/bd.png
// script.js:9 https://flagcdn.com/w320/dk.png
// script.js:9 https://flagcdn.com/w320/fm.png